### ISSUE TITLE
Updating dags

### ISSUE THREAD

**Issue by dgershman** [mumoshu/kube-airflow#1]
How are you handling the updating of dags without restarting the other containers?  Distributing the dags to all the different containers (dashboard, workers, schedulers).

**Comment by tkaymak** [comment]
I solved it via ConfigMaps https://kubernetes.io/docs/user-guide/configmap/

**Comment by martonpe** [comment]
@james-woods Can you elaborate a bit more on how you solved it via ConfigMaps? Do you build and version Docker containers that have the dags baked into them or do you use volumes or similar to get the code later?

**Comment by jrglee** [comment]
@james-woods one problem I noticed is configmaps, when mounted as volumes, creates a folder called `..data` and other folders with random names. The original file is just a symlink to those internal folders. Since airflow recursively scans the dags folder, you have the risk of getting the wrong path for each dag. This makes each pod have an unique path to the dag files. How did you manage to exclude the kube generated folders from the scan?

**Comment by tkaymak** [comment]
Hi sorry that I was not responding earlier,
I solved it via configmaps and I didnt care about the hidden files as Airflow is ignoring them anyway. 
It's not the cleanest solution, but it works. I am not using relative path calls in my airflow code, so it's not a dealbreaker for me.
@martonpe the configmaps hold all my DAG related data, I only bake the container when upgrading airflow and if I work on the DAGs I use configmaps or secrets, if I have secret files or API keys.

There is also the possibility to link single files and preserving the original content of a directory [described here](https://github.com/kubernetes/kubernetes/issues/19764#issuecomment-280913701), but I haven't tried that yet.

**Comment by jrglee** [comment]
The hidden files I mentioned were created by Kubernete's atomic writer https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/atomic_writer.go#L406. This is used by configmaps to write the data into volumes

Airflow recursively scans the dags folder so those duplicates are always included. The code uses `os.walk` to look for all `.py` files. I got it to work by adding an `.airflowignore` file with regex to ignore any path containing a directory starting with `..`.

The problem with those duplicates is the random names the parent directory can have. The scheduler will trigger a job which the workers can't see because their local paths are different. Since you are not facing this problem then maybe you are running airflow or kubernetes in a different version than mine. Or your workers are running in the same container than the scheduler.

**Comment by tkaymak** [comment]
@jrglee can you share your .airflowignore?

**Comment by jrglee** [comment]
Hey @james-woods, here is my config
```
$ cat .airflowignore
.*/\.\..+/.+\.py
```

Hope it can be helpful.

**Comment by giaosudau** [comment]
What if I include a package along?
package includes __init__ file?
```
error: "custom_operators/__init__.py" is not a valid key name for a ConfigMap: a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')
```

**Comment by tkaymak** [comment]
I think I will switch to baking the DAG's into the container soon, as having them as ConfigMaps sounds like an anti-pattern to me now. Airflow is following the principle of defining everything in the code  - so changing a DAG is a software change which should trigger a rebuild of the container in the Kubernetes paradigm. Also DAGs can have dependencies on other Python lib's - thus these need to be baked into the image anyway.

**Comment by martonpe** [comment]
@james-woods Coming from app development this is what I ended up doing as well. The problem with this approach is that you need to kill and recreate the worker pods every time you roll out and there is no easy way to shut them down gracefully. Which is not a problem if you only have short running tasks and not a lot of them, but if you do...

**Comment by gsemet** [comment]
ConfigMaps is not the ideal solution to convey DAGs. The best one is to have them directly within the container, but I agree this may not be ideal, since it requires a release management to automatically build new docker image on push and so on. 
The issue is with python dependencies, they need to be installed, and in container, you don't have pip, only the python executable. I'll open a new issue about that

**Comment by call** [comment]
I use [kubernetes/git-sync](https://github.com/kubernetes/git-sync) sidecar containers for my plugins and dags and it works very well. Changes are pushed to production as soon as I push to master branch, and the application does not need to be touched.

**Comment by mikeghen** [comment]
@call, does this refresh the dags or do you need to do something to restart the web/worker pods?

**Comment by mikeghen** [comment]
@call, any code/tutorials you could share about setting up the git-sync?
